In [2]:
import pandas as pd

df = pd.read_csv("vendas_autoveiculos_brasil_bcb.csv", sep=";")
display(df)

           data   valor
0    01/02/1981   65251
1    01/03/1981   64065
2    01/04/1981   69042
3    01/05/1981   62966
4    01/06/1981   61271
..          ...     ...
540  01/02/2026  184792
541  01/03/2026  262131
542  01/04/2026  242590
543  01/05/2026  257332
544  01/06/2026  251506

[545 rows x 2 columns]

In [3]:
df["data"] = pd.to_datetime(df["data"], format="%d/%m/%Y")

vendas_anos = df.groupby(df["data"].dt.year)["valor"].sum().reset_index()
display(vendas_anos)

    data    valor
0   1981   705397
1   1982   866436
2   1983   899700
3   1984   875133
4   1985   971706
5   1986  1050376
6   1987   927163
7   1988  1068215
8   1989  1015560
9   1990   899978
10  1991   963913
11  1992  1074861
12  1993  1174313
13  1994  1323427
14  1995  1453258
15  1996  1621351
16  1997  1849341
17  1998  1430993
18  1999  1286132
19  2000  1601206
20  2001  1671238
21  2002  1629039
22  2003  1747579
23  2004  2082657
24  2005  2350639
25  2006  2419717
26  2007  2820152
27  2008  3013784
28  2009  3020205
29  2010  3357443
30  2011  3328537
31  2012  3457054
32  2013  3625614
33  2014  3215208
34  2015  2571949
35  2016  2293428
36  2017  2761635
37  2018  2884915
38  2019  2923705
39  2020  2171148
40  2021  2242456
41  2022  2311921
42  2023  2360619
43  2024  2568637
44  2025  2720696
45  2026  1356725

In [4]:
import plotly.express as px

grafico = px.bar(x=vendas_anos["data"], y=vendas_anos["valor"], title="Analise de vendas de autoveiculos")
grafico.update_yaxes(title = "Valores")
grafico.update_xaxes(title= "Anos")
grafico.show()