In [1]:
import pandas as pd

tabela = pd.read_csv("selemob.csv", encoding="latin-1", sep=";")
display(tabela)

,Status,Carta-Consulta,Modalidade,UF,Município,Agente Financeiro,Proponente,Empreendimento,Valor de Contrapartida (R$),Valor de Empréstimo (R$),Valor de Investimento (R$)
0,Enquadrada pelo Gestor da Aplicação,3924.4.0702/2019,Estudos e Projetos,PR,Cascavel,Caixa Econômica Federal,Prefeitura Municipal de Cascavel,Estudos e Projetos do Prefeitura Municipal de ...,"R$ 75.000,00","R$ 1.425.000,00","R$ 1.500.000,00"
1,Enquadrada pelo Gestor da Aplicação,4052.23.1007/2019,Qualificação Viária,SP,Limeira,Caixa Econômica Federal,Prefeitura Municipal de Limeira,Qualificação Viária do Prefeitura Municipal de...,"R$ 2.233.325,32","R$ 42.433.181,00","R$ 44.666.506,32"
2,Enquadrada pelo Gestor da Aplicação,3851.4.2111/2018,Estudos e Projetos,SP,Mogi das Cruzes,Caixa Econômica Federal,Prefeitura Municipal de Mogi das Cruzes,Estudos e Projetos do Prefeitura Municipal de ...,"R$ 25.000,00","R$ 475.000,00","R$ 500.000,00"
3,Selecionada pelo gestor da aplicação,3960.23.0104/2019,Qualificação Viária,PA,Belém,Caixa Econômica Federal,Prefeitura Municipal de Belém,Qualificação Viária do Prefeitura Municipal de...,"R$ 7.367.519,74","R$ 139.982.875,03","R$ 147.350.394,77"
4,Enquadrada pelo Gestor da Aplicação,4056.3.1007/2019,Transporte Não Motorizado,SP,Limeira,Caixa Econômica Federal,Prefeitura Municipal de Limeira,Transporte Não Motorizado do Prefeitura Munici...,"R$ 266.405,11","R$ 5.061.696,97","R$ 5.328.102,08"
...,...,...,...,...,...,...,...,...,...,...,...
2287,Em análise de enquadramento,1485.2.0401/2018,Qualificação Viária,CE,Aracati,Caixa Econômica Federal,Prefeitura Municipal de Aracati,Qualificação Viária do Prefeitura Municipal de...,"R$ 559.979,17","R$ 10.639.604,21","R$ 11.199.583,38"
2288,Devolvida ao Proponente,1430.245.2712/2017,Qualificação Viária,PB,Santa Rita,Caixa Econômica Federal,Prefeitura Municipal de Santa Rita,Qualificação Viária do Prefeitura Municipal de...,"R$ 880.640,00","R$ 16.732.160,00","R$ 17.612.800,00"
2289,Devolvida ao Proponente,1615.24.1902/2018,Qualificação Viária,SC,Urussanga,Banco Regional de Desenvolvimento do Extremo S...,Prefeitura Municipal de Urussanga,Qualificação Viária do Prefeitura Municipal de...,"R$ 302.500,00","R$ 5.747.500,00","R$ 6.050.000,00"
2290,Em análise de enquadramento,723.24.0310/2017,Qualificação Viária,RS,Sarandi,Caixa Econômica Federal,Prefeitura Municipal de Sarandi,Qualificação Viária do Prefeitura Municipal de...,"R$ 265.891,61","R$ 5.051.940,49","R$ 5.317.832,10"
2291,Não enquadrada pelo Agente Financeiro,188.24.2208/2017,Qualificação Viária,PE,Pesqueira,Caixa Econômica Federal,Prefeitura Municipal de Pesqueira,Qualificação Viária do Prefeitura Municipal de...,"R$ 300.000,00","R$ 5.700.000,00","R$ 6.000.000,00"

In [14]:
df = tabela.copy()

for col in ["Valor de Contrapartida (R$)", "Valor de Empréstimo (R$)", "Valor de Investimento (R$)"]:
    df[col] = df[col].astype(str).replace("R$", "", regex=False).str.replace(" ", "",regex=False).str.replace(".","", regex=False).str.replace(".", ".", regex=False)
    df[col] = pd.to_numeric(df[col], errors="coerce")
display(df.head())

,Status,Carta-Consulta,Modalidade,UF,Município,Agente Financeiro,Proponente,Empreendimento,Valor de Contrapartida (R$),Valor de Empréstimo (R$),Valor de Investimento (R$)
0,Enquadrada pelo Gestor da Aplicação,3924.4.0702/2019,Estudos e Projetos,PR,Cascavel,Caixa Econômica Federal,Prefeitura Municipal de Cascavel,Estudos e Projetos do Prefeitura Municipal de ...,NaN,NaN,NaN
1,Enquadrada pelo Gestor da Aplicação,4052.23.1007/2019,Qualificação Viária,SP,Limeira,Caixa Econômica Federal,Prefeitura Municipal de Limeira,Qualificação Viária do Prefeitura Municipal de...,NaN,NaN,NaN
2,Enquadrada pelo Gestor da Aplicação,3851.4.2111/2018,Estudos e Projetos,SP,Mogi das Cruzes,Caixa Econômica Federal,Prefeitura Municipal de Mogi das Cruzes,Estudos e Projetos do Prefeitura Municipal de ...,NaN,NaN,NaN
3,Selecionada pelo gestor da aplicação,3960.23.0104/2019,Qualificação Viária,PA,Belém,Caixa Econômica Federal,Prefeitura Municipal de Belém,Qualificação Viária do Prefeitura Municipal de...,NaN,NaN,NaN
4,Enquadrada pelo Gestor da Aplicação,4056.3.1007/2019,Transporte Não Motorizado,SP,Limeira,Caixa Econômica Federal,Prefeitura Municipal de Limeira,Transporte Não Motorizado do Prefeitura Munici...,NaN,NaN,NaN