In [1]:
import pandas as pd 

tabela = pd.read_csv("Equipe_Nebula.csv")
display(tabela)

,Id,data_venda,vendedor,equipe,categoria_servico,servico,quantidade,preco_unitario,custo,cliente,estado,regiao
0,1,2022-08-04,Sarah,Equipe Nebula,Infraestrutura,Backup em Nuvem,1,1330.07,931.04,Viana,DF,centro-oeste
1,2,2023-10-15,Benício,Equipe Nebula,Consultoria,Auditoria de Sistemas,5,1149.22,947.22,Moreira S.A.,AM,norte
2,3,2023-09-12,Benício,Equipe Nebula,Consultoria,Consultoria em TI,3,802.19,432.31,Rodrigues - ME,BA,nordeste
3,4,2025-04-06,Renan,Equipe Nebula,Desenvolvimento,Automação de Processos,6,542.93,293.90,Duarte Moreira S/A,AM,norte
4,5,2024-11-23,Renan,Equipe Nebula,Consultoria,Treinamento em TI,17,687.27,517.24,da Rosa,RJ,sudeste
...,...,...,...,...,...,...,...,...,...,...,...,...
23007,23008,2025-03-22,Renan,Equipe Nebula,Consultoria,Treinamento em TI,10,1245.51,1005.20,Campos,PR,sul
23008,23009,2025-02-24,Julia,Equipe Nebula,Consultoria,Planejamento Estratégico de TI,8,233.41,132.08,Castro S/A,BA,nordeste
23009,23010,2023-06-03,Benício,Equipe Nebula,Consultoria,Treinamento em TI,20,1082.42,544.11,Rodrigues,SC,sul
23010,23011,2022-08-04,Julia,Equipe Nebula,Infraestrutura,Gerenciamento de Redes,6,583.52,398.52,Porto,MG,sudeste
23011,23012,2024-07-25,Vinicius,Equipe Nebula,Infraestrutura,Monitoramento de Sistemas,1,1419.95,915.69,Moura,SP,sudeste

In [2]:
df = tabela.copy()

In [3]:
df["total_vendas"] = df["quantidade"] * df["preco_unitario"]
df["custo_total"] = df["quantidade"] * df["custo"]
df["lucro"] = df["total_vendas"] - df["custo_total"]
df["margem_lucro"] = ((df["lucro"] / df["total_vendas"]) * 100).round(2)
display(df)

,Id,data_venda,vendedor,equipe,categoria_servico,servico,quantidade,preco_unitario,custo,cliente,estado,regiao,total_vendas,custo_total,lucro,margem_lucro
0,1,2022-08-04,Sarah,Equipe Nebula,Infraestrutura,Backup em Nuvem,1,1330.07,931.04,Viana,DF,centro-oeste,1330.07,931.04,399.03,30.00
1,2,2023-10-15,Benício,Equipe Nebula,Consultoria,Auditoria de Sistemas,5,1149.22,947.22,Moreira S.A.,AM,norte,5746.10,4736.10,1010.00,17.58
2,3,2023-09-12,Benício,Equipe Nebula,Consultoria,Consultoria em TI,3,802.19,432.31,Rodrigues - ME,BA,nordeste,2406.57,1296.93,1109.64,46.11
3,4,2025-04-06,Renan,Equipe Nebula,Desenvolvimento,Automação de Processos,6,542.93,293.90,Duarte Moreira S/A,AM,norte,3257.58,1763.40,1494.18,45.87
4,5,2024-11-23,Renan,Equipe Nebula,Consultoria,Treinamento em TI,17,687.27,517.24,da Rosa,RJ,sudeste,11683.59,8793.08,2890.51,24.74
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23007,23008,2025-03-22,Renan,Equipe Nebula,Consultoria,Treinamento em TI,10,1245.51,1005.20,Campos,PR,sul,12455.10,10052.00,2403.10,19.29
23008,23009,2025-02-24,Julia,Equipe Nebula,Consultoria,Planejamento Estratégico de TI,8,233.41,132.08,Castro S/A,BA,nordeste,1867.28,1056.64,810.64,43.41
23009,23010,2023-06-03,Benício,Equipe Nebula,Consultoria,Treinamento em TI,20,1082.42,544.11,Rodrigues,SC,sul,21648.40,10882.20,10766.20,49.73
23010,23011,2022-08-04,Julia,Equipe Nebula,Infraestrutura,Gerenciamento de Redes,6,583.52,398.52,Porto,MG,sudeste,3501.12,2391.12,1110.00,31.70
23011,23012,2024-07-25,Vinicius,Equipe Nebula,Infraestrutura,Monitoramento de Sistemas,1,1419.95,915.69,Moura,SP,sudeste,1419.95,915.69,504.26,35.51

In [4]:
# FATURAMENTO TOTAL DA EQUIPE NEBULA

faturamento_total = sum(df["total_vendas"])
print(f"{faturamento_total:,.2f}")

200,431,920.41

In [5]:
# LUCRO TOTAL 

lucro_total = sum(df["lucro"])
print(f"{lucro_total:,.2f}")

60,284,476.75

In [6]:
# VOLUME DE VENDAS POR VENDEDOR

analise_vendedores = df[["vendedor", "quantidade"]].groupby("vendedor").sum()
display(analise_vendedores.sort_values(by="quantidade", ascending=False))

          quantidade
vendedor
Vinicius       50413
Renan          49168
Benício        48420
Julia          47185
Sarah          46985

In [76]:
# RECEITA TOTAL DE CADA VENDEDOR

analise_receita = df[["vendedor", "total_vendas"]].groupby("vendedor").sum()
analise_receita["total_vendas"] = (analise_receita["total_vendas"]/1_000_000).round(2)
display(analise_receita.sort_values(by="total_vendas", ascending=False))

          total_vendas
vendedor
Vinicius         41.44
Renan            40.59
Benício          40.21
Julia            39.29
Sarah            38.90

In [8]:
# TABELA DE VENDAS DE SERVICOS POR QUANTIDADE

analise_servicos = df[["servico", "quantidade"]].groupby("servico").sum()
display(analise_servicos.sort_values(by="quantidade", ascending=False ))

                                quantidade
servico
Consultoria em TI                    17177
Hospedagem de Sites                  16788
Automação de Processos               16565
Gerenciamento de Redes               16492
Auditoria de Sistemas                16432
Treinamento em TI                    16360
Suporte Técnico                      16301
Gestão de Projetos de TI             16147
Criação de Aplicativos               15956
Backup em Nuvem                      15906
Desenvolvimento de Software          15883
Desenvolvimento Web                  15724
Monitoramento de Sistemas            15677
Integração de Sistemas               15394
Planejamento Estratégico de TI       15369

In [77]:
# TABELA DE SERVICOS POR RECEITA

analise_receita_srvç = df[["servico", "total_vendas"]].groupby("servico").sum()
analise_receita_srvç["total_vendas"] = (analise_receita_srvç["total_vendas"]/1_000_000).round(2)
display(analise_receita_srvç.sort_values(by="total_vendas", ascending=False))

                                total_vendas
servico
Treinamento em TI                      14.06
Consultoria em TI                      14.02
Hospedagem de Sites                    13.98
Automação de Processos                 13.95
Gerenciamento de Redes                 13.87
Auditoria de Sistemas                  13.63
Suporte Técnico                        13.45
Gestão de Projetos de TI               13.24
Criação de Aplicativos                 13.19
Desenvolvimento de Software            13.04
Backup em Nuvem                        12.94
Integração de Sistemas                 12.88
Monitoramento de Sistemas              12.83
Desenvolvimento Web                    12.67
Planejamento Estratégico de TI         12.67

In [78]:
# DISTRIBUICAO DE VENDAS POR ESTADO

analise_regioes = df[["total_vendas", "estado"]].groupby("estado").sum()
analise_regioes["total_vendas"] = (analise_regioes["total_vendas"]/1_000_000).round(2)
display(analise_regioes.sort_values(by="total_vendas", ascending=False))

        total_vendas
estado
PE             13.79
RJ             13.73
PA             13.70
GO             13.69
AM             13.52
SP             13.50
RO             13.45
DF             13.39
SC             13.33
MG             13.29
MT             13.24
PR             13.20
BA             13.02
CE             12.94
RS             12.66

In [11]:
# MARGEM DE LUCRO MEDIA POR SERVICO

margem_media_lucro = df[["servico","margem_lucro"]].groupby("servico").mean().round(2)
display(margem_media_lucro.sort_values(by="margem_lucro", ascending=False))

                                margem_lucro
servico
Auditoria de Sistemas                  30.43
Desenvolvimento de Software            30.35
Treinamento em TI                      30.29
Gestão de Projetos de TI               30.20
Suporte Técnico                        30.10
Monitoramento de Sistemas              30.05
Automação de Processos                 30.02
Backup em Nuvem                        30.02
Desenvolvimento Web                    29.97
Gerenciamento de Redes                 29.96
Criação de Aplicativos                 29.94
Planejamento Estratégico de TI         29.94
Consultoria em TI                      29.90
Integração de Sistemas                 29.89
Hospedagem de Sites                    29.48

In [12]:
# EVOLUCAO DA RECEITA POR ANO

df["data_venda"] = pd.to_datetime(df["data_venda"])

receita_anual = df[["data_venda", "total_vendas"]].groupby(pd.Grouper(key="data_venda", freq="YE")).sum().sort_index(ascending=True)
receita_anual["Receita R$ M"] = (receita_anual["total_vendas"]/1_000_000).round(2)
receita_anual["Variacao %"] = (receita_anual["Receita R$ M"].pct_change()*100).round(2)
display(receita_anual)

            total_vendas  Receita R$ M  Variacao %
data_venda
2022-12-31   39256861.47         39.26         NaN
2023-12-31   66448674.60         66.45       69.26
2024-12-31   67922988.76         67.92        2.21
2025-12-31   26803395.58         26.80      -60.54

In [13]:
# MARGEM DE LUCRO MEDIA DE CADA VENDEDOR

margem_lucro_vendedores = df[["vendedor", "margem_lucro"]].groupby("vendedor").mean().round(2)
display(margem_lucro_vendedores.sort_values(by="margem_lucro", ascending=False))

          margem_lucro
vendedor
Julia            30.38
Renan            30.21
Benício          29.95
Vinicius         29.85
Sarah            29.80

In [75]:
# TICKET MEDIO POR SERVICO

ticket_medio_srvç = df[["servico", "total_vendas"]].groupby("servico").sum()
ticket_medio_srvç["total_vendas"] = (ticket_medio_srvç["total_vendas"]/1_000_000).round(2)
display(ticket_medio_srvç.sort_values(by="total_vendas", ascending=False))

                                total_vendas
servico
Treinamento em TI                      14.06
Consultoria em TI                      14.02
Hospedagem de Sites                    13.98
Automação de Processos                 13.95
Gerenciamento de Redes                 13.87
Auditoria de Sistemas                  13.63
Suporte Técnico                        13.45
Gestão de Projetos de TI               13.24
Criação de Aplicativos                 13.19
Desenvolvimento de Software            13.04
Backup em Nuvem                        12.94
Integração de Sistemas                 12.88
Monitoramento de Sistemas              12.83
Desenvolvimento Web                    12.67
Planejamento Estratégico de TI         12.67

In [74]:
# RELACAO DE FATURAMENTO DA EMPRESA POR CLIENTE

fat_por_cliente = df[["cliente", "total_vendas"]].groupby("cliente").sum()
display(fat_por_cliente.sort_values(by="total_vendas", ascending=False))

                        total_vendas
cliente
Cardoso                   3166610.34
da Rosa                   1744385.70
Moreira                   1711296.63
Costela                   1650938.99
Porto                     1650106.37
...                              ...
Gomes Caldeira Ltda.          169.49
Castro da Paz e Filhos        167.68
da Cruz Alves S.A.            162.91
Pinto Souza S.A.              158.79
Cardoso da Rocha S/A          154.39

[5697 rows x 1 columns]

In [ ]:
# RANK DE EFICIENCIA POR VENDEDOR 

ranking_eficiencia = df.groupby("vendedor", as_index=False).agg(lucro_total = ("lucro", "sum"), qtd_total = ("quantidade", "sum"))

ranking_eficiencia["rentabilidade_venda"] = ranking_eficiencia["lucro_total"]/ranking_eficiencia["qtd_total"]

ranking_eficiencia = ranking_eficiencia.sort_values(by="rentabilidade_venda", ascending=False).reset_index(drop=True)

ranking_eficiencia["lucro_total"] = (ranking_eficiencia["lucro_total"]/1_000_000).round(2)

ranking_eficiencia["rentabilidade_venda"] = ranking_eficiencia["rentabilidade_venda"].round(2)
ranking_eficiencia["lucro_total"] = ranking_eficiencia["lucro_total"].round(2)
display(ranking_eficiencia)

   vendedor  lucro_total  qtd_total  rentabilidade_venda
0     Julia        11.91      47185               252.36
1     Renan        12.31      49168               250.42
2   Benício        12.04      48420               248.59
3     Sarah        11.64      46985               247.79
4  Vinicius        12.39      50413               245.67

In [69]:
# QUANTO CADA SERVICO REPRESENTA DO FATURAMENTO TOTAL DA EMPRESA

faturamento_servico = df.groupby("servico",  as_index=False)["total_vendas"].sum()
#faturamento_total = df["total_vendas"].sum()
faturamento_servico["percentual"] = (faturamento_servico["total_vendas"]/faturamento_total)*100
faturamento_servico = faturamento_servico.sort_values(by="percentual", ascending=False)
faturamento_servico["total_vendas"] = (faturamento_servico["total_vendas"]/1_000_000).round(2)
faturamento_servico["percentual"] = faturamento_servico["percentual"].round(2)

faturamento_servico["percentual_fmt"] = faturamento_servico["percentual"].astype(str)+"%"
display(faturamento_servico)

                           servico  total_vendas  percentual percentual_fmt
14               Treinamento em TI         14.06        7.01          7.01%
3                Consultoria em TI         14.02        7.00           7.0%
9              Hospedagem de Sites         13.98        6.97          6.97%
1           Automação de Processos         13.95        6.96          6.96%
7           Gerenciamento de Redes         13.87        6.92          6.92%
0            Auditoria de Sistemas         13.63        6.80           6.8%
13                 Suporte Técnico         13.45        6.71          6.71%
8         Gestão de Projetos de TI         13.24        6.61          6.61%
4           Criação de Aplicativos         13.19        6.58          6.58%
6      Desenvolvimento de Software         13.04        6.50           6.5%
2                  Backup em Nuvem         12.94        6.46          6.46%
10          Integração de Sistemas         12.88        6.42          6.42%
11       Monitoramento de Sistemas         12.83        6.40           6.4%
12  Planejamento Estratégico de TI         12.67        6.32          6.32%
5              Desenvolvimento Web         12.67        6.32          6.32%

In [68]:
# RELACAO DO LUCRO ENTRE REGIAO E CATEGORIA

lucro_cat_reg = df.groupby(["regiao", "categoria_servico"]).agg(Total_vendas = ("total_vendas", "sum"))
lucro_cat_reg["Total_vendas"] = (lucro_cat_reg["Total_vendas"]/1_000_000).round(2)
display(lucro_cat_reg)

                                Total_vendas
regiao       categoria_servico
centro-oeste Consultoria               13.55
             Desenvolvimento           13.29
             Infraestrutura            13.46
nordeste     Consultoria               13.61
             Desenvolvimento           12.93
             Infraestrutura            13.20
norte        Consultoria               13.91
             Desenvolvimento           12.76
             Infraestrutura            14.00
sudeste      Consultoria               13.64
             Desenvolvimento           13.75
             Infraestrutura            13.12
sul          Consultoria               12.92
             Desenvolvimento           12.98
             Infraestrutura            13.29

In [ ]:
# iDENTIFICANDO O MOTIVO DA QUEDA DE 60% NO FATURAMENTO ANUAL DA EMLRESA EM 2025

df["ano"] = df["data_venda"].dt.year
df["mes"] = df["data_venda"].dt.month_name(locale="pt_BR.utf8")
df["mes_num"] = df["data_venda"].dt.month

df_2025 = df[df["ano"]==2025]
faturamento_mes = df_2025.groupby(["mes_num", "mes"], as_index=False).agg(Faturamento_total = ("total_vendas", "sum"))

display(faturamento_mes.sort_values(by="Faturamento_total", ascending=False))

# COMO PODEMOS ANALISAR NA TABELA ABAIXO, HOUVE REGISTRO DE FATURAMENTO SOMENTE NOS MESES DE JANEIRO, MARCO, ABRIL E MAIO. POR SE TRATAR DE UMA BASE DE DAODS SINTETICOS, NAO POSSO AFIRMAR SE A AUSENCIA DOS DEMAIS MESES SE DEU PELA FALTA DE FATURAMENTO NELES OU PELA FALTA DE REGISTRO

   mes_num        mes  Faturamento_total
0        1    Janeiro         5597319.10
2        3      Março         5597264.73
3        4      Abril         5327237.43
1        2  Fevereiro         5192119.82
4        5       Maio         5089454.50